[workspace]
members = ["contracts"]

[workspace.package]
version = "0.1.0"
edition = "2024_07"

[workspace.dependencies]
assert_macros = "2.11.4"
snforge_std = "0.44.0"
starknet = "2.11.4"
openzeppelin = "1.0.0"

